//Setting up data as a reusable component
export const homeObjOne = {
    id: 'about', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions',
    description: 'This is describing the app', 
    buttonLabel: 'Get Started',
    imgStart: true, 
    img: require('../../Images/background.jpg'),
    alt: 'Description',
    dark: true, 
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'projects', 
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Take A Look At Some Of My Recent Projects',
    headline: 'More to Come Soon!',
    description: 'This is describing the app', 
    buttonLabel: 'Get Started',
    imgStart: true, 
    img: require('../../Images/me.jpg'),
    alt: 'Description',
    dark: true, 
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'contact', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions',
    description: 'This is describing the app', 
    buttonLabel: 'Get Started',
    imgStart: true, 
    img: require('../../Images/background.jpg'),
    alt: 'Description',
    dark: true, 
    primary: true,
    darkText: false,
}